default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ssc_product_support_development
  username: postgres
  password: <%= ENV['DEV_PASSWORD'] %>

test:
  <<: *default
  database: ssc_product_support_test
  username: postgres
  password: <%= ENV['DEV_PASSWORD'] %>

production:
  <<: *default
  database: ssc_product_support_production
  username: postgres
  password: <%= ENV['DEV_PASSWORD'] %>