UserRole.create ([
	{ name: 'Administrator', description: 'Create, read, update, and delete all objects' },
	{ name: 'Subject Matter Expert', description: 'Create, update, and delete products; Read-only for all other objects' },
	{ name: 'Internal Reader', description: 'Read-only for all objects' },
	{ name: 'External Reader', description: 'Read-only for non-protected information' }
])

User.create ([
	{ core_id: 'administratorTest', first_name: 'Administrator', last_name: 'Test', email: 'admin.test@motorolasolutions.com', password_digest: User.digest('password'), user_role: 1 },
	{ core_id: 'subjectMatterExpertTest', first_name: 'Subject Matter Expert', last_name: 'Test', email: 'sme.test@motorolasolutions.com', password_digest: User.digest('password'), user_role: 2 },
	{ core_id: 'internalReaderTest', first_name: 'Internal Reader', last_name: 'Test', email: 'int-reader.test@motorolasolutions.com', password_digest: User.digest('password'), user_role: 3 },
	{ core_id: 'externalReaderTest', first_name: 'External Reader', last_name: 'Test', email: 'ext-reader.test@motorolasolutions.com', password_digest: User.digest('password'), user_role: 4 }
])

Day.create([
	{ name: 'Sunday' },
	{ name: 'Monday' },
	{ name: 'Tuesday' },
	{ name: 'Wednesday' },
	{ name: 'Thursday' },
	{ name: 'Friday' },
	{ name: 'Saturday' }
])

SupportCenter.create([
	{ name: 'Not Applicable' },
	{ name: 'Unknown' },
	{ name: 'North America & Latin America (NALA) Solution Support Center (SSC)' },
	{ name: 'Europe, Middle East, & Africa (EMEA) Solution Support Center (SSC)' },
	{ name: 'Asia & Pacific (AP) Solution Support Center (SSC)' },
	{ name: 'North America (NA) Marketing Call Center (MCC)' }
])

SupportFunction.create([
	{ name: 'Not Applicable' },
	{ name: 'Unknown' },
	{ name: 'Other' },
	{ name: 'Service Desk' },
	{ name: 'Technical Support' }
])

JobType.create([
	{ name: 'Not Applicacble' },
	{ name: 'Unknown' },
	{ name: 'Presale' },
	{ name: 'Order' },
	{ name: 'Return' },
	{ name: 'Warranty Replacement' },
	{ name: 'Technical Support' },
	{ name: 'Repair' }
])

SourceLocation.create([
	{ name: 'Not Applicable' },
	{ name: 'Unknown' },
	{ name: 'Dropship' },
	{ name: 'External' }
])

SourceType.create([
	{ name: 'Not Applicable' },
	{ name: 'Unknown' },
	{ name: 'Internal' },
	{ name: 'External' }
])

Company.create([
	{ name: 'Not Applicable' },
	{ name: 'Unknown' },
	{ name: 'Motorola Solutions', website: 'http://www.motorolasolutions.com/' },
	{ name: 'Vertex Standard', website: 'http://www.vertexstandard.com/' },
	{ name: 'Emergency CallWorks', website: 'https://www.emergencycallworks.com/' },
	{ name: 'Zebra Technologies', website: 'https://www.zebra.com/' },
	{ name: 'Motorola Mobility', website: 'http://www.motorola.com/' },
	{ name: 'Cambium Networks', website: 'http://www.cambiumnetworks.com/' },
	{ name: 'NICE Systems', website: 'http://www.nice.com/' },
	{ name: 'Airbus DS Communications', website: 'http://www.airbus-dscomm.com/' },
	{ name: 'VMware', website: 'http://www.vmware.com/' },
	{ name: 'Futurecom', website: 'http://www.futurecom.com/' }
])

Servicer.create([
	{ name: 'Motorola Solutions Service Center, El Paso', address_1: '1220 Don Haskins Drive', address_2: 'Suite A', city: 'El Paso', state_province: 'TX', postal_code: '79936', country: 'United States' },
	{ name: 'Motorola Solutions Service Center, Elgin - Subscriber', name: 'Motorola Solutions Service Center', address_1: '2204 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Motorola Solutions Service Center, Elgin - Laptops', name: 'Motorola Solutions Service Center', address_1: '2208 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Motorola Solutions Service Center, Elgin - Test Equipment', name: 'Motorola Solutions Service Center', address_1: '2216 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Motorola Solutions Infrastructure Depot Operations (IDO)', name: 'Motorola Solutions IDO Repair', address_1: '2214 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Motorola Solutions Federal Technical Center (FTC)', name: 'Motorola Solutions Federal Technical Center', address_1: '10105 Senate Drive', city: 'Lanham', state_province: 'MD', postal_code: '20706', country: 'United States' },
	{ name: 'Motorola Solutions Canadian Technical Logistics Center (CTLC)', name: 'Motorola Solutions Canadian Technical Logistics Center', address_1: '181 Whitehall Drive', city: 'Markham', state_province: 'Ontario', postal_code: 'L3R 9T1', country: 'Canada' },
	{ name: 'Motorola Solutions Returned Goods', name: 'Motorola Solutions Returned Goods', address_1: '2222 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Motorola Solutions Warranty Department', name: 'Motorola Solutions Warranty Department', address_1: '2222 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Vertex Standard Service Center', name: 'Vertex Standard Service Center', address_1: '7201-A Intermodal Drive', city: 'Louisville', state_province: 'KY', postal_code: '40258', country: 'United States' },
	{ name: 'Futurecom', name: 'Futurecom Systems Group Inc', address_1: '3277 Langstaff Road', city: 'Concord', state_province: 'Ontario', postal_code: 'L4K 5P8', country: 'Canada' }
])

Agent.create([
	{ name: 'Customer Care Services (CCS) - Canada Support' },
	{ name: 'Customer Care Services (CCS) - Consumer Radio' },
	{ name: 'Customer Care Services (CCS) - Dealer Support' },
	{ name: 'Customer Care Services (CCS) - Domestic Parts' },
	{ name: 'Customer Care Services (CCS) - Federal Government' },
	{ name: 'Customer Care Services (CCS) - International Support' },
	{ name: 'Customer Care Services (CCS) - Learning Management System (LMS)' },
	{ name: 'Customer Care Services (CCS) - Motorola Online (MOL)' },
	{ name: 'Customer Care Services (CCS) - Parts Identification' },
	{ name: 'Customer Care Services (CCS) - Partner Interaction Center (PIC) and Partner Program' },
	{ name: 'Customer Care Services (CCS) - Portal Support' },
	{ name: 'Customer Care Services (CCS) - Business Radio Support' },
	{ name: 'Customer Care Services (CCS) - Rental Support' },
	{ name: 'Customer Care Services (CCS) - Repair Services' },
	{ name: 'iDEN - Dispatch Services' },
	{ name: 'iDEN - Existing Cases' },
	{ name: 'iDEN - iBSC' },
	{ name: 'iDEN - Melody' },
	{ name: 'iDEN - OMC' },
	{ name: 'iDEN - Overall' },
	{ name: 'iDEN - Packet' },
	{ name: 'iDEN - Portal' },
	{ name: 'iDEN - Switching' },
	{ name: 'Presale Marketing' },
	{ name: 'Presale Technical' },
	{ name: 'Smart Public Safety Solutions (SPSS) - CAD' },
	{ name: 'Smart Public Safety Solutions (SPSS) - CommandCentral' },
	{ name: 'Smart Public Safety Solutions (SPSS) - Citizen Service Request (CSR) 311' },
	{ name: 'Smart Public Safety Solutions (SPSS) - Jail Systems Management' },
	{ name: 'Smart Public Safety Solutions (SPSS) - Law Records Management System (LRMS)' },
	{ name: 'Smart Public Safety Solutions (SPSS) - Mobile Applications' },
	{ name: 'Smart Public Safety Solutions (SPSS) - Records Management System (RMS)' },
	{ name: 'Technical Support Operations (TSO) - APX Subscribers' },
	{ name: 'Technical Support Operations (TSO) - ASTRO Legacy Subscribers' },
	{ name: 'Technical Support Operations (TSO) - ASTRO25' },
	{ name: 'Technical Support Operations (TSO) - Capacity MAX' },
	{ name: 'Technical Support Operations (TSO) - MOTOTRBO Connect Plus' },
	{ name: 'Technical Support Operations (TSO) - Consoles' },
	{ name: 'Technical Support Operations (TSO) - ASTRO Consoles' },
	{ name: 'Technical Support Operations (TSO) - CPO' },
	{ name: 'Technical Support Operations (TSO) - Data Infrastructure' },
	{ name: 'Dispatch Services - Dispatch' },
	{ name: 'Technical Support Operations (TSO) - Field Workforce Management (FWM) Support' },
	{ name: 'Technical Support Operations (TSO) - iDEN Support' },
	{ name: 'Technical Support Operations (TSO) - MOTOTRBO IP Site Connect' },
	{ name: 'Technical Support Operations (TSO) - LTE HANDHELD' },
	{ name: 'Technical Support Operations (TSO) - LTE PROV' },
	{ name: 'Technical Support Operations (TSO) - LTE TSO' },
	{ name: 'Technical Support Operations (TSO) - LTE VSM' },
	{ name: 'Technical Support Operations (TSO) - MC Series Desksets & Paging' },
	{ name: 'Dispatch Services - Navy' },
	{ name: 'Technical Support Operations (TSO) - Network Monitoring Operations (NMO)' },
	{ name: 'Technical Support Operations (TSO) - Network Monitoring Operations (NMO), Case Closure' },
	{ name: 'Technical Support Operations (TSO) - Network Monitoring Operations (NMO), Department of Defense (DOD)' },
	{ name: 'Technical Support Operations (TSO) - Professional & Commercial Radio (PCR) Analog Subscribers' },
	{ name: 'Technical Support Operations (TSO) - Premier MDC PSA' },
	{ name: 'Dispatch Services - Part Request' },
	{ name: 'Technical Support Operations (TSO) - Real Time Crime Center (RTCC)' },
	{ name: 'Technical Support Operations (TSO) - Smartnet' },
	{ name: 'Technical Support Operations (TSO) - Security Operations Center (SOC)' },
	{ name: 'Technical Support Operations (TSO) - Technical Support' },
	{ name: 'Technical Support Operations (TSO) - MOTOTRBO Applications' },
	{ name: 'Technical Support Operations (TSO) - MOTOTRBO Digital Conventional' },
	{ name: 'Technical Support Operations (TSO) - TSO MSIP' },
	{ name: 'Technical Support Operations (TSO) - Remote Service Delivery (RSD)' },
	{ name: 'Technical Support Operations (TSO) - XTS & XTL Subscribers' },
	{ name: 'Vertex Standard - Customer Service' },
	{ name: 'Vertex Standard - Technical Support' },
	{ name: 'Vertex Standard - Vertex Standard Online (VSOL)' }
])

Split.create([
	{ name: 'EMB NA Switchboard - 8002914209 (Reynosa)' },
	{ name: 'MSVC Tier 1 SUPT - SPAIN (+Consum)' },
	{ name: 'XEMB LMS NALA 1 English - (new Zebra) NALA Entitlement team' },
	{ name: 'XGPS-AP JA CSNT Japanese' },
	{ name: 'XGPS-AP JA Pre-Sales Japanese' },
	{ name: 'XGPS-AP JA TAC Japanese' },
	{ name: 'XGPS-CCS CA English' },
	{ name: 'XGPS-CCS French 5/24/2016' },
	{ name: 'XGPS-CCS Consumer' },
	{ name: 'XGPS-CCS Dealer Support' },
	{ name: 'XGPS-CCS Dom Parts' },
	{ name: 'XGPS-CCS Fed Govt 3/31/2015' },
	{ name: 'XGPS-CCS French Translator' },
	{ name: 'XGPS-CCS INTL Eng 3/31/2015' },
	{ name: 'XGPS-CCS INTL SP 3/31/2015' },
	{ name: 'XGPS-CCS Lead Assist' },
	{ name: 'XGPS-CCS LMS' },
	{ name: 'XGPS-CCS MOL' },
	{ name: 'XGPS-CCS Parts ID' },
	{ name: 'XGPS-CCS PIC and Partner Program' },
	{ name: 'XGPS-CCS Portal Support' },
	{ name: 'XGPS-CCS Radio Repair' },
	{ name: 'XGPS-CCS RBR Support 04012016' },
	{ name: 'XGPS-CCS Rental 3/31/2015' },
	{ name: 'XGPS-CCS Services' },
	{ name: 'XGPS-CCS Spanish' },
	{ name: 'XGPS-EA English 5552075' },
	{ name: 'XGPS-EA French 5552076' },
	{ name: 'XGPS-EA German 5552077 3/15/2016' },
	{ name: 'XGPS-EA Hebrew 5552078' },
	{ name: 'XGPS-EA Italian 5552079' },
	{ name: 'XGPS-EA Polish 5552080' },
	{ name: 'XGPS-EA Russian 5552081' },
	{ name: 'XGPS-EA Spanish 5552082' },
	{ name: 'XGPS-IDEN Dispatch' },
	{ name: 'XGPS-IDEN Existing Case' },
	{ name: 'XGPS-IDEN iBSC' },
	{ name: 'XGPS-IDEN Melody' },
	{ name: 'XGPS-IDEN OMC' },
	{ name: 'XGPS-IDEN Overall' },
	{ name: 'XGPS-IDEN Packet' },
	{ name: 'XGPS-IDEN Portal' },
	{ name: 'XGPS-IDEN Switching' },
	{ name: 'XGPS-LA Customer Service English5551003' },
	{ name: 'XGPS-LA Customer Service Spanish 5551087' },
	{ name: 'XGPS-LA PIC Portuguese 5551000' },
	{ name: 'XGPS-LA PIC Spanish 5551001' },
	{ name: 'XGPS-LA PORTAL English 5551099' },
	{ name: 'XGPS-LA PORTAL Spanish 5551004' },
	{ name: 'XGPS-LA Tech Support Consumer 5551091' },
	{ name: 'XGPS-LA Tech Support English 05/29/2015' },
	{ name: 'XGPS-LA Tech Support Spanish 5/29/2015' },
	{ name: 'XGPS-LA TRBO Spanish 5551006' },
	{ name: 'XGPS-MS Admin PAL 5553001' },
	{ name: 'XGPS-MS Billing PAL 5553002' },
	{ name: 'XGPS-MS NOC 5553003' },
	{ name: 'XGPS-MS Training PAL 5553003' },
	{ name: 'XGPS-Presale Marketing 12/15/2015 ' },
	{ name: 'XGPS-Presale Technical 12/15/2015 ' },
	{ name: 'XGPS-PSA CAD' },
	{ name: 'XGPS-PSA CC 4/27/2016' },
	{ name: 'XGPS-PSA CSR 311' },
	{ name: 'XGPS-PSA Jail Sys' },
	{ name: 'XGPS-PSA LRMS' },
	{ name: 'XGPS-PSA Mob Apps' },
	{ name: 'XGPS-PSA RMS' },
	{ name: 'XGPS-SSC APX' },
	{ name: 'XGPS-SSC Astro Legacy Subs' },
	{ name: 'XGPS-SSC Astro25' },
	{ name: 'XGPS-SSC Capacity MAX' },
	{ name: 'XGPS-SSC Connect Plus' },
	{ name: 'XGPS-SSC Console' },
	{ name: 'XGPS-SSC Console Astro' },
	{ name: 'XGPS-SSC CPO' },
	{ name: 'XGPS-SSC Data Infrastructure' },
	{ name: 'XGPS-SSC Dispatch Services' },
	{ name: 'XGPS-SSC FWM Support' },
	{ name: 'XGPS-SSC IDEN SUPPORT' },
	{ name: 'XGPS-SSC IP Site Connect' },
	{ name: 'XGPS-SSC LTE HANDHELD' },
	{ name: 'XGPS-SSC LTE PROV' },
	{ name: 'XGPS-SSC LTE TSO' },
	{ name: 'XGPS-SSC LTE VSM' },
	{ name: 'XGPS-SSC MC Series Deskset' },
	{ name: 'XGPS-SSC Navy' },
	{ name: 'XGPS-SSC NMO' },
	{ name: 'XGPS-SSC NMO Case Closure' },
	{ name: 'XGPS-SSC NMO DOD' },
	{ name: 'XGPS-SSC PCR Analog' },
	{ name: 'XGPS-SSC Premier MDC PSA' },
	{ name: 'XGPS-SSC Return Authorization' },
	{ name: 'XGPS-SSC RTCC' },
	{ name: 'XGPS-SSC Smartnet' },
	{ name: 'XGPS-SSC SOC' },
	{ name: 'XGPS-SSC Spanish' },
	{ name: 'XGPS-SSC Technical Support' },
	{ name: 'XGPS-SSC TRBO Apps' },
	{ name: 'XGPS-SSC TRBO Digital Conv' },
	{ name: 'XGPS-SSC TSO MSIP' },
	{ name: 'XGPS-SSC TSO Remote Service 2/22/2016' },
	{ name: 'XGPS-SSC WLAAN [Zebra]' },
	{ name: 'XGPS-SSC WLAN Install & Projects [Zebra]' },
	{ name: 'XGPS-SSC XTS/XTL' },
	{ name: 'XGPS-SSC Training Team 8/26/2015' },
	{ name: 'XGPS-SSC Vertex Cust Svc' },
	{ name: 'XGPS-SSC Vertex Tech Support' },
	{ name: 'XGPS-SSC Vertex VSOL' }
])