UserRole.create ([
	{ name: 'Administrator', description: 'Create, read, update, and delete all objects' },
	{ name: 'Subject Matter Expert', description: 'Create, update, and delete products; Read-only for all other objects' },
	{ name: 'Internal Reader', description: 'Read-only for all objects' },
	{ name: 'External Reader', description: 'Read-only for non-protected information' }
])

User.create ([
	{ core_id: 'administratorTest', first_name: 'Administrator', last_name: 'Test', email: 'admin.test@motorolasolutions.com', password_digest: User.digest('password'), user_role: 1 },
	{ core_id: 'subjectMatterExpertTest', first_name: 'Subject Matter Expert', last_name: 'Test', email: 'sme.test@motorolasolutions.com', password_digest: User.digest('password'), user_role: 2 },
	{ core_id: 'internalReaderTest', first_name: 'Internal Reader', last_name: 'Test', email: 'int-reader.test@motorolasolutions.com', password_digest: User.digest('password'), user_role: 3 },
	{ core_id: 'externalReaderTest', first_name: 'External Reader', last_name: 'Test', email: 'ext-reader.test@motorolasolutions.com', password_digest: User.digest('password'), user_role: 4 }
])

Day.create([
	{ name: 'Sunday' },
	{ name: 'Monday' },
	{ name: 'Tuesday' },
	{ name: 'Wednesday' },
	{ name: 'Thursday' },
	{ name: 'Friday' },
	{ name: 'Saturday' }
])

SupportCenter.create([
	{ name: 'Not Applicable' },
	{ name: 'Unknown' },
	{ name: 'North America & Latin America (NALA) Solution Support Center (SSC)' },
	{ name: 'Europe, Middle East, & Africa (EMEA) Solution Support Center (SSC)' },
	{ name: 'Asia & Pacific (AP) Solution Support Center (SSC)' },
	{ name: 'North America (NA) Marketing Call Center (MCC)' }
])

SupportFunction.create([
	{ name: 'Not Applicable' },
	{ name: 'Unknown' },
	{ name: 'Other' },
	{ name: 'Service Desk' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support' }
])

JobType.create([
	{ name: 'Not Applicacble' },
	{ name: 'Unknown' },
	{ name: 'Presale' },
	{ name: 'Order' },
	{ name: 'Return' },
	{ name: 'Warranty Replacement' },
	{ name: 'Technical Support' },
	{ name: 'Repair' }
])

SourceLocation.create([
	{ name: 'Not Applicable' },
	{ name: 'Unknown' },
	{ name: 'Dropship' }
])

SourceType.create([
	{ name: 'Not Applicable' },
	{ name: 'Unknown' },
	{ name: 'Internal' },
	{ name: 'External' }
])

Company.create([
	{ name: 'Not Applicable' },
	{ name: 'Unknown' },
	{ name: 'Motorola Solutions', website: 'http://www.motorolasolutions.com/' },
	{ name: 'Vertex Standard', website: 'http://www.vertexstandard.com/' },
	{ name: 'Emergency CallWorks', website: 'https://www.emergencycallworks.com/' },
	{ name: 'Zebra Technologies', website: 'https://www.zebra.com/' },
	{ name: 'Motorola Mobility', website: 'http://www.motorola.com/' },
	{ name: 'Cambium Networks', website: 'http://www.cambiumnetworks.com/' },
	{ name: 'NICE Systems', website: 'http://www.nice.com/' },
	{ name: 'Airbus DS Communications', website: 'http://www.airbus-dscomm.com/' },
	{ name: 'VMware', website: 'http://www.vmware.com/' },
	{ name: 'Futurecom', website: 'http://www.futurecom.com/' }
])

Servicer.create([
	{ name: 'Not Available'},
	{ name: 'Unknown' },
	{ name: 'Motorola Solutions Service Center, El Paso', address_1: '1220 Don Haskins Drive', address_2: 'Suite A', city: 'El Paso', state_province: 'TX', postal_code: '79936', country: 'United States' },
	{ name: 'Motorola Solutions Service Center, Elgin - Subscriber', address_1: '2204 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Motorola Solutions Service Center, Elgin - Laptops', address_1: '2208 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Motorola Solutions Service Center, Elgin - Test Equipment', address_1: '2216 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Motorola Solutions Infrastructure Depot Operations (IDO)', address_1: '2214 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Motorola Solutions Federal Technical Center (FTC)', address_1: '10105 Senate Drive', city: 'Lanham', state_province: 'MD', postal_code: '20706', country: 'United States' },
	{ name: 'Motorola Solutions Canadian Technical Logistics Center (CTLC)', address_1: '181 Whitehall Drive', city: 'Markham', state_province: 'Ontario', postal_code: 'L3R 9T1', country: 'Canada' },
	{ name: 'Motorola Solutions Returned Goods', address_1: '2222 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Motorola Solutions Warranty Department', address_1: '2222 Galvin Drive', city: 'Elgin', state_province: 'IL', postal_code: '60124', country: 'United States' },
	{ name: 'Vertex Standard Service Center', address_1: '7201-A Intermodal Drive', city: 'Louisville', state_province: 'KY', postal_code: '40258', country: 'United States' },
	{ name: 'Futurecom', address_1: '3277 Langstaff Road', city: 'Concord', state_province: 'Ontario', postal_code: 'L4K 5P8', country: 'Canada' }
])

Agent.create([
	{ support_function_id: 1, support_center_id: 1, name: 'Not Available' },
	{ support_function_id: 2, support_center_id: 2, name: 'Unknown' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Canada Support' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Consumer Radio' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Dealer Support' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Domestic Parts' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Federal Government' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - International Support' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Learning Management System (LMS)' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Motorola Online (MOL)' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Parts Identification' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Partner Interaction Center (PIC) and Partner Program' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Portal Support' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Business Radio Support' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Rental Support' },
	{ support_function_id: 4, support_center_id: 3, name: 'Customer Care Services (CCS) - Repair Services' },
	{ support_function_id: 5, support_center_id: 3, name: 'iDEN - Dispatch' },
	{ support_function_id: 5, support_center_id: 3, name: 'iDEN - Existing Cases' },
	{ support_function_id: 5, support_center_id: 3, name: 'iDEN - iBSC' },
	{ support_function_id: 5, support_center_id: 3, name: 'iDEN - Melody' },
	{ support_function_id: 5, support_center_id: 3, name: 'iDEN - OMC' },
	{ support_function_id: 5, support_center_id: 3, name: 'iDEN - Overall' },
	{ support_function_id: 5, support_center_id: 3, name: 'iDEN - Packet' },
	{ support_function_id: 5, support_center_id: 3, name: 'iDEN - Portal' },
	{ support_function_id: 5, support_center_id: 3, name: 'iDEN - Switching' },
	{ support_function_id: 4, support_center_id: 6, name: 'Marketing Call Center (MCC) - Presale Marketing' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Presale Technical' },
	{ support_function_id: 5, support_center_id: 3, name: 'Smart Public Safety Solutions (SPSS) - Computer Aided Dispatch (CAD)' },
	{ support_function_id: 5, support_center_id: 3, name: 'Smart Public Safety Solutions (SPSS) - CommandCentral' },
	{ support_function_id: 5, support_center_id: 3, name: 'Smart Public Safety Solutions (SPSS) - Citizen Service Request (CSR) 311' },
	{ support_function_id: 5, support_center_id: 3, name: 'Smart Public Safety Solutions (SPSS) - Jail Systems Management' },
	{ support_function_id: 5, support_center_id: 3, name: 'Smart Public Safety Solutions (SPSS) - Law Records Management System (LRMS)' },
	{ support_function_id: 5, support_center_id: 3, name: 'Smart Public Safety Solutions (SPSS) - Mobile Applications' },
	{ support_function_id: 5, support_center_id: 3, name: 'Smart Public Safety Solutions (SPSS) - Records Management System (RMS)' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - APX Subscribers' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - ASTRO Legacy Subscribers' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - ASTRO25' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Capacity MAX' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - MOTOTRBO Connect Plus' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Consoles' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - ASTRO Consoles' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - CPO' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Data Infrastructure' },
	{ support_function_id: 4, support_center_id: 3, name: 'Dispatch Services - Dispatch' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Field Workforce Management (FWM) Support' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - iDEN Support' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - MOTOTRBO IP Site Connect' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - LTE HANDHELD' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - LTE PROV' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - LTE TSO' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - LTE VSM' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - MC Series Desksets & Paging' },
	{ support_function_id: 4, support_center_id: 3, name: 'Dispatch Services - Navy' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Network Management Operations (NMO)' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Network Management Operations (NMO), Case Closure' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Network Management Operations (NMO), Department of Defense (DOD)' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Professional & Commercial Radio (PCR) Analog Subscribers' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Premier MDC PSA' },
	{ support_function_id: 4, support_center_id: 3, name: 'Dispatch Services - Part Request' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Real Time Crime Center (RTCC)' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Smartnet' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Security Operations Center (SOC)' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Technical Support' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - MOTOTRBO Applications' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - MOTOTRBO Digital Conventional' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - TSO MSIP' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - Remote Service Delivery (RSD)' },
	{ support_function_id: 5, support_center_id: 3, name: 'Technical Support Operations (TSO) - XTS & XTL Subscribers' },
	{ support_function_id: 4, support_center_id: 3, name: 'Vertex Standard - Customer Service' },
	{ support_function_id: 5, support_center_id: 3, name: 'Vertex Standard - Technical Support' },
	{ support_function_id: 4, support_center_id: 3, name: 'Vertex Standard - Vertex Standard Online (VSOL)' }
])

Split.create([
	{ name: 'XGPS-CCS CA English', agent: 1 },
	{ name: 'XGPS-CCS French 5/24/2016', agent: 1 },
	{ name: 'XGPS-CCS Consumer', agent: 2 },
	{ name: 'XGPS-CCS Dealer Support', agent: 3 },
	{ name: 'XGPS-CCS Dom Parts', agent: 4 },
	{ name: 'XGPS-CCS Fed Govt 3/31/2015', agent: 5 },
	{ name: 'XGPS-CCS INTL Eng 3/31/2015', agent: 6 },
	{ name: 'XGPS-CCS INTL SP 3/31/2015', agent: 6 },
	{ name: 'XGPS-CCS LMS', agent: 7 },
	{ name: 'XGPS-CCS MOL', agent: 8 },
	{ name: 'XGPS-CCS Parts ID', agent: 9 },
	{ name: 'XGPS-CCS PIC and Partner Program', agent: 10 },
	{ name: 'XGPS-CCS Portal Support', agent: 11 },
	{ name: 'XGPS-CCS Radio Repair', agent: 14 },
	{ name: 'XGPS-CCS RBR Support 04012016', agent: 12 },
	{ name: 'XGPS-CCS Rental 3/31/2015', agent: 13 },
	{ name: 'XGPS-CCS Services', agent: 14 },
	{ name: 'XGPS-IDEN Dispatch', agent: 15 },
	{ name: 'XGPS-IDEN Existing Case', agent: 16 },
	{ name: 'XGPS-IDEN iBSC', agent: 17 },
	{ name: 'XGPS-IDEN Melody', agent: 18 },
	{ name: 'XGPS-IDEN OMC', agent: 19 },
	{ name: 'XGPS-IDEN Overall', agent: 20 },
	{ name: 'XGPS-IDEN Packet', agent: 21 },
	{ name: 'XGPS-IDEN Portal', agent: 22 },
	{ name: 'XGPS-IDEN Switching', agent: 23 },
	{ name: 'XGPS-Presale Marketing 12/15/2015', agent: 24 },
	{ name: 'XGPS-Presale Technical 12/15/2015', agent: 25 },
	{ name: 'XGPS-PSA CAD', agent: 26 },
	{ name: 'XGPS-PSA CC 4/27/2016', agent: 27 },
	{ name: 'XGPS-PSA CSR 311', agent: 28 },
	{ name: 'XGPS-PSA Jail Sys', agent: 29 },
	{ name: 'XGPS-PSA LRMS', agent: 30 },
	{ name: 'XGPS-PSA Mob Apps', agent: 31 },
	{ name: 'XGPS-PSA RMS', agent: 32 },
	{ name: 'XGPS-SSC APX', agent: 33 },
	{ name: 'XGPS-SSC Astro Legacy Subs', agent: 34 },
	{ name: 'XGPS-SSC Astro25', agent: 35 },
	{ name: 'XGPS-SSC Capacity MAX', agent: 36 },
	{ name: 'XGPS-SSC Connect Plus', agent: 37 },
	{ name: 'XGPS-SSC Console', agent: 38 },
	{ name: 'XGPS-SSC Console Astro', agent: 39 },
	{ name: 'XGPS-SSC CPO', agent: 40 },
	{ name: 'XGPS-SSC Data Infrastructure', agent: 41 },
	{ name: 'XGPS-SSC Dispatch Services', agent: 42 },
	{ name: 'XGPS-SSC FWM Support', agent: 43 },
	{ name: 'XGPS-SSC IDEN SUPPORT', agent: 44 },
	{ name: 'XGPS-SSC IP Site Connect', agent: 45 },
	{ name: 'XGPS-SSC LTE HANDHELD', agent: 46 },
	{ name: 'XGPS-SSC LTE PROV', agent: 47 },
	{ name: 'XGPS-SSC LTE TSO', agent: 48 },
	{ name: 'XGPS-SSC LTE VSM', agent: 49 },
	{ name: 'XGPS-SSC MC Series Deskset', agent: 50 },
	{ name: 'XGPS-SSC Navy', agent: 51 },
	{ name: 'XGPS-SSC NMO', agent: 52 },
	{ name: 'XGPS-SSC NMO Case Closure', agent: 53 },
	{ name: 'XGPS-SSC NMO DOD', agent: 54 },
	{ name: 'XGPS-SSC PCR Analog', agent: 55 },
	{ name: 'XGPS-SSC Premier MDC PSA', agent: 56 },
	{ name: 'XGPS-SSC Return Authorization', agent: 57 },
	{ name: 'XGPS-SSC RTCC', agent: 58 },
	{ name: 'XGPS-SSC Smartnet', agent: 59 },
	{ name: 'XGPS-SSC SOC', agent: 60 },
	{ name: 'XGPS-SSC Technical Support', agent: 61 },
	{ name: 'XGPS-SSC TRBO Apps', agent: 62 },
	{ name: 'XGPS-SSC TRBO Digital Conv', agent: 63 },
	{ name: 'XGPS-SSC TSO MSIP', agent: 64 },
	{ name: 'XGPS-SSC TSO Remote Service 2/22/2016' , agent: 65 },
	{ name: 'XGPS-SSC XTS/XTL', agent: 66 },
	{ name: 'XGPS-SSC Vertex Cust Svc', agent: 67 },
	{ name: 'XGPS-SSC Vertex Tech Support', agent: 68 },
	{ name: 'XGPS-SSC Vertex VSOL', agent: 69 }
])

Phone.create([
	{ phonable_type: 'Agent', phonable_id: 42, number: '8002217144', option: ['1'] },
	{ phonable_type: 'Agent', phonable_id: 57, number: '8002217144', option: ['1', '3'] },
	{ phonable_type: 'Agent', phonable_id: 59, number: '8002217144', option: ['2', '1', '1'] },
	{ phonable_type: 'Agent', phonable_id: 35, number: '8002217144', option: ['2', '1', '2'] },
	{ phonable_type: 'Agent', phonable_id: 41, number: '8002217144', option: ['2', '2', '1'] },
	{ phonable_type: 'Agent', phonable_id: 39, number: '8002217144', option: ['2', '3', '1'] },
	{ phonable_type: 'Agent', phonable_id: 38, number: '8002217144', option: ['2', '1', '2'] },
	{ phonable_type: 'Agent', phonable_id: 27, number: '8002217144', option: ['2', '5'] },
	{ phonable_type: 'Agent', phonable_id: 26, number: '8002217144', option: ['2', '6', '1'] },
	{ phonable_type: 'Agent', phonable_id: 32, number: '8002217144', option: ['2', '6', '2'] },
	{ phonable_type: 'Agent', phonable_id: 31, number: '8002217144', option: ['2', '6', '3'] },
	{ phonable_type: 'Agent', phonable_id: 29, number: '8002217144', option: ['2', '6', '4'] },
	{ phonable_type: 'Agent', phonable_id: 30, number: '8002217144', option: ['2', '6', '5'] },
	{ phonable_type: 'Agent', phonable_id: 28, number: '8002217144', option: ['2', '6', '6'] },
	{ phonable_type: 'Agent', phonable_id: 9, number: '8002217144', option: ['3', '1'] },
	{ phonable_type: 'Agent', phonable_id: 33, number: '8002217144', option: ['3', '3'] },
	{ phonable_type: 'Agent', phonable_id: 55, number: '8002217144', option: ['3', '4'] },
	{ phonable_type: 'Agent', phonable_id: 50, number: '8002217144', option: ['3', '5'] },
	{ phonable_type: 'Agent', phonable_id: 25, number: '8002217144', option: ['3', '6'] },
	{ phonable_type: 'Agent', phonable_id: 52, number: '8002217144', option: ['5'] },
	{ phonable_type: 'Agent', phonable_id: 53, number: '8002217144', option: ['5'] },
	{ phonable_type: 'Agent', phonable_id: 54, number: '8002217144', option: ['5'] }
])

Product.create([
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Si300', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/body-worn-cameras/si300/Si300-Body-Camera.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Si500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/body-worn-cameras/Si500/Si500_Front_324x324.jpg#3' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'LEX L10', image_url: 'http://www.motorolasolutions.com/content/dam/msi/docs/products/lte-user-devices/product-lex-755-bart-lipinski0551_w_megaLEX_Activity_6.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'VML 750', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/public_safety_lte/vml750/_images/vml750_front_angle_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CRYPTR 2', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios_-_public_safety/encryption/ame1000/cryptr_micro_encryption_unit/_images/cryptr-micro-web-324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CRYPTR micro', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios_-_public_safety/encryption/ame1000/cryptr_micro_encryption_unit/_images/cryptr-micro-web-324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'VML700', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/public_safety_lte/vml700/_images/static_files/vml700_lg-us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'UM1000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/public_safety_lte/_images/um1000-angle-transp-324x324.jpg#2' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MW810', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/mobile_computers/vehicle-mounted_computers/mw810/_images/static_files/primary-mw810-3up-white-324x324.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'ADVISOR II', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/pagers/advisor_ii/_images/static_files/b2b_advisor_ii_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MINITOR IV' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MINITOR V', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/pagers/minitor_v/_images/static_files/b2b_product_minitor_v_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MINITOR VI', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/pagers/minitor_vi/_images/staticfiles/minitor_vi_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 8000XE', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/apx/apx8000xe/APX8000XE_Front_324x324.jpg#4' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 8000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/apx_8000/APX8000_Front_2.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 7000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/apx_7000/_images/static_files/apx_7000_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 6000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/apx_6000/_images/staticfiles/apx_6000_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 4000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/apx_4000_p25/_images/_staticfiles/apx-4000_m3_front.jpg#3' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 7000XE', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/apx_7000xe/_images/staticfiles/apx7000xe_yellow_front_raised_view_copy.jpg#4' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 6000XE', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/apx6000xe/images/static_files/apx6000_ex_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 7000L', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/apx_7000l/_images/apx_7000l_main_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 3000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/apx_3000_p25/_images/apx_3000_lg_front.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 1000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/apx/APX1000/APX_1000_Image1_LG.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'SRX 2200', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/srx2200/_images/_staticfiles/srx2200_lg5.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 4000XH', image_url: 'http://www.motorolasolutions.com/content/dam/msi/docs/products/two-way-radios/apx/apx-images/APX4000XH_front_with_mic_reed.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 6500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/_images/_static_files/02_control_head_green_front_copy.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX Mobile Siren and Light Interface Module', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/interface_modules/apx_mls_interface_module/_images/apx_mobile_slim_front_main_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX Dual Radio', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios_-_public_safety/mobile_radios_gps/apx_dual_radio/_images/apx_dual_radio_main_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 4500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios_-_public_safety/mobile_radios_gps/apx_4500/_images/_staticfiles/apx4500_lg2.jpg#2' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 7500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/_images/_static_files/07_control_head_black_a_front_copy.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Digital Vehicular Repeater System (DVRS)', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios_-_public_safety/repeaters/digital_vehicular_repeater_system__dvrs_/_images/static_files/digital_vehicular_repeater_system_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'APX 1500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/apx_1500/_images/apx1500_main_324x324_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'VRX1000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios_-_public_safety/repeaters/vrx1000/_images/_static_files/vrx1000_main_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'ASTRO SPECTRA Locomotive' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'ASTRO SPECTRA Motorcycle' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'ASTRO SPECTRA Plus', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/astro_digital_spectra_plus/_images/static_files/b2b_product_astro_digital_spectr_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'SPECTRA', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/astro_spectra_series/_images/b2b_product_spectra_md_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Saber I R' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Saber II R' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Saber' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XTS 5000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/government_and_public_safety_portable_radios/xts_5000/_images/static_files/b2b_product_xts_5000_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XTS 3500', image_url: '' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XTS 2500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/government_and_public_safety_portable_radios/xts2500/_images/static_files/b2b_product_xts2500_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XTS 1500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/government_and_public_safety_portable_radios/xts1500/_images/static_files/b2b_product_xts1500_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'ASTRO XTL 5000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/b2b_product_xtl5000_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'ASTRO 25 XTL 2500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/government_and_public_safety_mobile_radios/xtl_2500/_images/static_files/b2b_product_xtl_2500_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'ASTRO XTL 1500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/government_and_public_safety_mobile_radios/xtl_1500/_images/static_files/b2b_product_xtl1500_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 5000e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/mobile-radios/xpr5000e/xpr5000e_1_324x324.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 5550e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/mobile-radios/xpr5000e/xpr5000e_1_324x324.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 5580e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/mobile-radios/xpr5000e/xpr5000e_1_324x324.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 5350e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/mobile-radios/xpr5000e/xpr5000e_1_324x324.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 5380e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/mobile-radios/xpr5000e/xpr5000e_1_324x324.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CM200d', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/cm300d/images/cm200d_lg.jpg#2' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CM300d', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/cm300d/images/cm300d_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 5350', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/xpr5550/_images/_staticfiles/xpr5550_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 5380', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/xpr5550/_images/_staticfiles/xpr5550_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 5550', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/xpr5550/_images/_staticfiles/xpr5550_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 5580', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/xpr5550/_images/_staticfiles/xpr5550_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 4350', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr4000_series/mototrbo_xpr_4380_angledl_324x324.jpg#2' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 4380', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr4000_series/mototrbo_xpr_4380_angledl_324x324.jpg#2' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 4550', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr4000_series/mototrbo_xpr_4580_angledl_324x324.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 4580', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr4000_series/mototrbo_xpr_4580_angledl_324x324.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 2500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/product_lines/mototrbo/mobiles/xpr2500/_images/_staticfiles/mototrbo_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 7550e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/portable-radios/XPR7000e/XPR7000e-FKP_Front_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 7580e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/portable-radios/XPR7000e/XPR7000e-FKP_Front_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 7350e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/portable-radios/XPR7000e/XPR7000e-FKP_Front_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 7380e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/portable-radios/XPR7000e/XPR7000e-FKP_Front_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 3500e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/portable-radios/XPR3000e/XPR3000e-LKP_Front_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 3300e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/portable-radios/XPR3000e/XPR3000e-LKP_Front_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'SL 7550e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/portable-radios/SL7000e/SL7000e_Front_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'SL 7580e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/portable-radios/SL7000e/SL7000e_Front_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'SL 7590e', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/mototrbo/portable-radios/SL7000e/SL7000e_Front_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CP200d', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/cp200d/image/cp200d_front_lg.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'SL 7550', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/sl7550/_images/_staticfiles/sl7550_lg_537x522.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'SL 7580', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/sl7550/_images/_staticfiles/sl7550_lg_537x522.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'SL 7590', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/sl7550/_images/_staticfiles/sl7550_lg_537x522.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'SL 300', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/sl300/_images/_staticfiles/sl300_right_lg.jpg#3' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 6580 IS', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr6580is/images/xpr_6580_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 7550', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr7550/_images/_staticfiles/xpr7550_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 7350', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr7550/_images/_staticfiles/xpr7550_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 7580', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr7550/_images/_staticfiles/xpr7550_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 7380', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr7550/_images/_staticfiles/xpr7550_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 6100', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr_6350/_images/static_files/b2b_product_xpr6350_lg_us-en.jpg#3' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 6350', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr_6350/_images/static_files/b2b_product_xpr6350_lg_us-en.jpg#3' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 6380', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr_6350/_images/static_files/b2b_product_xpr6350_lg_us-en.jpg#3' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 6550', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr_6550/_images/static_files/b2b_product_xpr6550_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 6580', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr_6550/_images/static_files/b2b_product_xpr6550_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 3300', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr3300/_images/_staticfiles/xpr3300_lg3.jpg#6' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 3500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr3300/_images/_staticfiles/xpr3300_lg3.jpg#6' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 7550 IS', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr7550-is/_images/_staticfiles/csa_front_fkp_refinery_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 6300', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr_6300/_images/static_files/b2b_product_xpr6300_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XPR 6500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/xpr_6500/_images/static_files/b2b_product_xpr6500_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CLP1010', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/clp1010/_images/staticfiles/clp_1010_lg2.jpg#2' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CLP1040', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/clp1040/_images/staticfiles/clp1040_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CLP1060', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/clp1060/images/clp_withbt_front_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CLS1110', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/cls1110/_images/static_files/b2b_product_cls1110_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CLS1410', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/cls1410/_images/static_files/b2b_product_cls1410_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'DLR1020', image_url: 'http://www.motorolasolutions.com/content/dam/msi/docs/products/two-way-radios/on-site-business-radios/dlr-series-radio-images/DLR_front_reed.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'DLR1060', image_url: 'http://www.motorolasolutions.com/content/dam/msi/docs/products/two-way-radios/on-site-business-radios/dlr-series-radio-images/DLR_front_reed.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'DTR410', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/dtr410/_images/static_files/b2b_product_dtr410_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'DTR550', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/dtr550/_images/static_files/b2b_product_dtr550_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RDU4100', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/rdu4100/_images/_static_files/rdu4100_4w_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RDU4160D', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/rdu4160d/_images/_static_files/rdu4160d_4w_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RDV5100', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/rdv5100/_images/_static_files/rdv5100_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RMU2040', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/on-site_small_business/_images/_static/rmu2040_rmm2050_rmu2043_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RMU2043', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/on-site_small_business/_images/_static/rmu2040_rmm2050_rmu2043_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RMM2050', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/on-site_small_business/_images/_static/rmu2040_rmm2050_rmu2043_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RMU2080', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios_and_pagers_-_business/_images/rmu2080_rva50_xt420_nondisp_front.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RMU2080D', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/on-site_small_business/_images/_static/rmu2080d_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RMV2080', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/on-site_small_business/_images/_static/rmu2080_rmv2080_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RDU2020', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/on-site_small_business/rdu2020/_image/_static_files/rdu2020_2w_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RDU2080D', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/rdu2080d/_images/rdu2080d_2w_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RDV2020', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/on-site_small_business/rdv2020/_images/_staticfiles/rdv2020_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'RDV2080D', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/rdv2080d/_images/_static_files/rdv2080d_front_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CDM1550 LS+', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/cdm1550-ls_plus/_images/static_files/b2b_product_cdm1550_ls_mobile_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CDM1250', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/cdm1250/_images/static_files/b2b_product_cdm1250_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CM200', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/cm200/_images/static_files/b2b_product_cm200_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CDM1550', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/cdm1550/_images/static_files/b2b_product_cdm1550_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CDM750', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/cdm750/_images/static_files/b2b_product_cdm750_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'PM1200', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/pm1500/_images/static_files/b2b_product_pm1500_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CM300', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/cm300/_images/static_files/b2b_product_cm300_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'PM1500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/pm1500/_images/static_files/b2b_product_pm1500_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'PM400', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/wide_area_large_business_mobile_radios/pm400/_images/static_files/b2b_product_pm400_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Mag One BPR40', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/bpr40/_images/static_files/b2b_product_bpr40_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Mag One BPR20', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/BPR/BPR20/BPR20_34Left_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CP110 Display', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/on-site_small_business/cp110/cp110_display_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CP110 Non-Display', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/mobile_radios/on-site_small_business/cp110nondisplay/_images/_staticfiles/cp110_no_display_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CP185', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/cp185/_images/staticfile/cp185_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CP200', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/_images/_static_files/cp200_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'DTR650', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/dtr650/_images/static_files/b2b_product_dtr650_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'EX500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/ex500/_images/static_files/b2b_ex500_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'EX600-XLS', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/ex600/_images/static_files/b2b_product_ex600_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'EX560-XLS', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/ex560-xls/_images/static_files/ex560xls_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'HT1250', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/ht1250/_images/static_files/ht1250_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MT 1500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/mt_1500/_images/_staticfiles/mt1500portaltwowayradio_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'HT750', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/ht750/_images/static_files/b2b_product_ht750_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'HT1250 LS+', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/ht1250ls/_images/static_files/ht1250_ls_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'PR1500', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios_and_pagers_-_business/_images/_static_files/pr1500portaltwowayradio.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'PR400', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/pr400/_images/static_files/pr400_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'PR860', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/pr860/_images/static_files/b2b_product_pr860_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'VL50', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/vl50/_images/static_files/b2b_product_vl50_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'AXV5100', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/axv5100/_images/static_files/b2b_product_axv5100_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CP125', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/cp125/_images/static_files/b2b_product_cp125_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CP100', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/cp100/_images/static_files/b2b_cp100_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'CP150', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/cp150/_images/static_files/product_cp150_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'EX600' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'HT1250 LS' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'HT1250-XLS', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/ht1550-xls/_images/ht1550xls_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MTX8250', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/mt_1500/_images/_staticfiles/mtx8259_md.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MTX-LS' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MTX8250-LS', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/mtx8250-ls/_images/static_files/mtx8250ls_md.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MTX850', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/mtx850/_images/static_files/mtx850_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MTX850-LS', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/mtx850-ls/_images/_staticfiles/mtx850ls_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MTX9000', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/mtx9000/_images/static_files/b2b_product_mtx9000_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MTX9250', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/mtx9250/_images/static_files/b2b_product_mtx9250_md_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MTX950', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/wide_area_large_business_portable_radios/mtx950/_images/static_files/b2b_product_mtx950_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'VISAR' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XU1100', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/xu1100/_images/static_files/product_xu1100_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'VL130' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XU2100', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/xu2100/_images/static_files/b2b_product_xu2100_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XV2100', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/xv2100/_images/static_files/b2b_product_xv2100_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'XV1100', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/two-way_radios/portable_radios/small_business_portable_radios/xv1100/_images/static_files/b2b_product_xv1100_lg_us-en.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T605 H20', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/consumer/talkabout-radios/t-series/t605/T605_CaseRadiosChargerOnly_324x324.jpg#1' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T600 H2O', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/consumer/talkabout-radios/t-series/t600/T600_TwoRadios_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T480', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/consumer/talkabout-radios/T480-front-600x600.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T465', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/consumer/talkabout-radios/t-series/product-T465-w-screen-front-0526.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T460', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/consumer/talkabout-radios/t-series/product-T460-w-screen-front-0501.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T400', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/consumer/talkabout-radios/t-series/product-T400-w-screen-front-0493.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T260', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/consumer/talkabout-radios/t-series/t260/T260_2Radios_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T200', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/consumer/talkabout-radios/t-series/t200/T200_2Radios_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T107', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/consumer/talkabout-radios/t-series/t100-t107/t107/T107_TwoRadios_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T100', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/products/two-way-radios/consumer/talkabout-radios/t-series/t100-t107/t100/T100_TwoRadios_324x324.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MU350R', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/mg160a/_staticfiles/mu350_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MU354R', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/mu354r/_images/mu354_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MS355R', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/ms355r/images/ms355r.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MS350R Talkabout Two-Way Radio', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/talkabout_ms350r/_images/b2b_product_ms350_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MT352TPR', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/mt352tpr/images/mt352tpr.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MT350R Two-Way Radio', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/mt350r/images/mt350.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MT352R', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/mt352r/images/mt352r.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MR355R', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/talkabout-mr355r-two-way-radio/_images/_staticfiles/mr355r_lg.png' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MR350TPR', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/mr350tpr/_images/mr350tpr_3front.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MR350R Talkabout Two-Way Radio', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/talkabout-mr350r-two-way-radio/_images/_staticfiles/mr350r_lg.png' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MJ270R', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/talkabout-mj270r-two-way-radio/_images/_staticfiles/mj270_lg.png' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MH230TPR', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/mh230tpr/images/mh230tpr_collect.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'MH230R Talkabout Two-Way Radio', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/talkabout-mh230r-two-way-radio/_images/_staticfiles/mh230r_lg.png' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MD207R', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/mg160a/_staticfiles/md207r_pair_rgb_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MD200TPR', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/md200tpr/images/md200tpr.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MD200R', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/md200r/images/md200r.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MG160A', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/mg160a/_staticfiles/mg160_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout MG167A', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/mg160a/_staticfiles/mg167_lg.jpg' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout FV300', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/talkabout-fv300-two-way-radio/_images/_staticfiles/fv300_lg.png' },
	{ source_type_id: 3, source_location_id: 2, company_id: 3, name: 'Talkabout T9680RSAME', image_url: 'http://www.motorolasolutions.com/content/dam/msi/images/business/products/consumertwo-wayradios/talkabout-t9680rsame-two-way-radio/_images/_staticfiles/t9680rsame_lg.png' }
])

SupportJob.create([
	{ product_id: 1, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 2, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 3, agent_id: 48, job_type: 7, condition: 'All' },
	{ product_id: 4, agent_id: 48, job_type: 7, condition: 'All' },
	{ product_id: 5, agent_id: 43, job_type: 7, condition: 'All' },
	{ product_id: 6, agent_id: 43, job_type: 7, condition: 'All' },
	{ product_id: 7, agent_id: 48, job_type: 7, condition: 'All' },
	{ product_id: 8, agent_id: 51, job_type: 7, condition: 'All' },
	{ product_id: 9, agent_id: 43, job_type: 7, condition: 'All' },
	{ product_id: 10, agent_id: 52, job_type: 7, condition: 'All' },
	{ product_id: 11, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 12, agent_id: 52, job_type: 7, condition: 'All' },
	{ product_id: 13, agent_id: 52, job_type: 7, condition: 'All' },
	{ product_id: 14, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 15, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 16, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 17, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 18, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 19, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 20, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 21, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 22, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 23, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 24, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 25, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 26, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 27, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 28, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 29, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 30, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 31, agent_id: 44, job_type: 7, condition: 'All' }, # Add note referring Dispatch Sevices to etech36081
	{ product_id: 32, agent_id: 35, job_type: 7, condition: 'All' },
	{ product_id: 33, agent_id: 44, job_type: 7, condition: 'All' }, # Add note referring Dispatch Sevices to etech36081
	{ product_id: 34, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 35, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 36, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 37, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 38, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 39, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 40, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 41, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 42, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 43, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 44, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 45, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 46, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 47, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 48, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 48, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 49, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 49, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 50, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 50, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 51, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 51, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 52, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 52, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 53, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 53, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 54, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 54, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 55, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 55, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 56, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 56, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 57, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 57, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 58, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 58, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 59, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 59, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 60, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 60, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 61, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 61, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 62, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 62, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 63, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 63, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 64, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 64, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 65, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 65, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 66, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 66, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 67, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 67, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 68, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 68, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 69, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 69, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 70, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 70, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 71, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 71, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 72, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 72, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 73, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 73, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 74, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 74, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 75, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 75, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 76, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 76, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 77, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 77, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 78, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 78, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 79, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 79, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 80, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 80, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 81, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 81, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 82, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 82, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 83, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 83, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 84, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 84, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 85, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 85, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 86, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 86, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 87, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 87, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 88, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 88, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 89, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 89, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 90, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 90, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 91, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 91, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 92, agent_id: 47, job_type: 7, condition: 'If utilized in an IP Site Connect system' },
	{ product_id: 92, agent_id: 65, job_type: 7, condition: 'If utilized in a Digital Conventional system' },
	{ product_id: 93, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 94, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 95, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 96, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 97, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 98, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 99, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 100, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 101, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 102, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 103, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 104, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 105, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 106, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 107, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 108, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 109, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 110, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 111, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 112, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 113, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 114, agent_id: 14, job_type: 7, condition: 'All' },
	{ product_id: 115, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 116, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 117, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 118, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 119, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 120, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 121, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 122, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 123, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 124, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 125, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 126, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 127, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 128, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 129, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 130, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 131, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 132, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 133, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 134, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 135, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 136, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 137, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 138, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 139, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 140, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 141, agent_id: 57, job_type: 7, condition: 'All' },
	{ product_id: 142, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 143, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 144, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 145, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 146, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 147, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 148, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 149, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 150, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 151, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 152, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 153, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 154, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 155, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 156, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 157, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 158, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 159, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 160, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 161, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 162, agent_id: 1, job_type: 7, condition: 'All' },
	{ product_id: 163, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 164, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 165, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 166, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 167, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 168, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 169, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 170, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 171, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 172, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 173, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 174, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 175, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 176, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 177, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 178, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 179, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 180, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 181, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 182, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 183, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 184, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 185, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 186, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 187, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 188, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 189, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 190, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 191, agent_id: 4, job_type: 7, condition: 'All' },
	{ product_id: 192, agent_id: 4, job_type: 7, condition: 'All' }
])

ServiceJob.create([
	{ product_id: 1, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 2, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 3, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 4, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 5, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 6, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 7, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 8, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 9, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 10, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 11, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 12, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 13, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 14, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 15, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 16, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 17, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 18, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 19, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 20, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 21, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 22, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 23, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 24, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 25, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 26, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 27, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 28, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 29, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 30, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 31, servicer_id: 13, job_type: 8, condition: 'All' },
	{ product_id: 32, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 33, servicer_id: 13, job_type: 8, condition: 'All' },
	{ product_id: 34, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 35, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 36, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 37, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 38, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 39, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 40, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 41, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 42, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 43, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 44, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 45, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 46, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 47, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 48, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 49, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 50, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 51, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 52, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 53, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 54, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 55, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 56, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 57, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 58, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 59, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 60, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 61, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 62, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 63, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 64, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 65, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 66, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 67, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 68, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 69, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 70, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 71, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 72, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 73, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 74, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 75, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 76, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 77, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 78, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 79, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 80, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 81, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 82, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 83, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 84, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 85, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 86, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 87, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 88, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 89, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 90, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 91, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 92, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 93, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 94, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 95, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 96, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 97, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 98, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 99, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 100, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 101, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 102, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 103, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 104, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 105, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 106, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 107, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 108, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 109, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 110, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 111, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 112, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 113, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 114, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 115, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 116, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 117, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 118, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 119, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 120, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 121, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 122, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 123, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 124, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 125, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 126, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 127, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 128, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 129, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 130, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 131, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 132, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 133, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 134, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 135, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 136, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 137, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 138, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 139, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 140, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 141, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 142, servicer_id: 3, job_type: 8, condition: 'All' },
	{ product_id: 143, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 144, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 145, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 146, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 147, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 148, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 149, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 150, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 151, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 152, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 153, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 154, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 155, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 156, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 157, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 158, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 159, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 160, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 161, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 162, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 163, servicer_id: 1, job_type: 8, condition: 'All' },
	{ product_id: 164, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 165, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 166, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 167, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 168, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 169, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 170, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 171, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 172, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 173, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 174, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 175, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 176, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 177, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 178, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 179, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 180, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 181, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 182, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 183, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 184, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 185, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 186, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 187, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 188, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 189, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 190, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 191, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 192, servicer_id: 2, job_type: 8, condition: 'All' },
	{ product_id: 193, servicer_id: 2, job_type: 8, condition: 'All' }
])